api_user = person "API User" "A customer that predeominantly uses the API."
normal_user = person "Normal User" "A customer that uses the web or mobile applications."
admin_user = person "Admin User" "An Administrative user."
service_desk_user = person "Service Desk User" "A Service Desk user."
external_observability_user = person "External Observability User" "An external user that monitors the system for errors and performance."
